detectors:
  - name: DataStageConnectionCredentials
    keywords:
      - password
      - server
      - "\\V"
      - iisenc
    regex:
      dsx_hardcoded_password_leading: '(?i)F\d+\s+"([A-Za-z][A-Za-z0-9]*[0-9@#%^&*!]+[A-Za-z0-9@#%^&*!]*)\\V'
      dsx_hardcoded_password_trailing: '(?i)\\V([A-Za-z][A-Za-z0-9]*[0-9@#%^&*!]+[A-Za-z0-9@#%^&*!]*)"'
