detectors:
  - name: DataStageConnectionCredentials
    keywords:
      - password
      - server
      - "\\V"
    regex:
      dsx_hardcoded_password: '(?i)F\d+\s+"([^"\\]*[0-9@#$%^&*!._-][^"\\]*)\\V([^"\\]+)\\V([^"\\]+)"'
